### ISSUE TITLE
Feature: `ValidatableObject` add `Validate` method

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/BB84.Notifications#112]
**Is your feature request related to a problem? Please describe.**
There is not really a method to revalidate the whole model. At the moment this is only possible if a property is set.

**Describe the solution you'd like**
It would be cool to have a function that completely re-validates the model, captures any errors and returns the entire result as a `Boolean` expression.

**Describe alternatives you've considered**
Not sure what else to use.

**Comment by BoBoBaSs84** [comment]
I will look into it when I find the time. Sounds reasonable.

**Comment by Probotus** [comment]
Thx

**Comment by BoBoBaSs84** [comment]
Made the changes, there is going to be a new method and also a new property to check for all properties within the object.
