### ISSUE TITLE
Reversible property

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/BB84.Notifications#130]
**Is your feature request related to a problem? Please describe.**
It's not really a problem but I think it would be cool to have a `ReversibleProperty` in addition to the `NotifiableProperty`.

**Describe the solution you'd like**
With the help of the `ReversibleProperty` you can then:
- Switch the values back and forth again
- Select the number of values to be saved?
- This gives you the option of resetting values again

**Describe alternatives you've considered**
I don't know.

**Comment by BoBoBaSs84** [comment]
I already thought of something like that. It would require a backing list instead of a backing field or maybe both.

**Comment by BoBoBaSs84** [comment]
@Probotus Maybe you have the time to do some testing?

**Comment by Probotus** [comment]
I'll try to do a few tests over the course of the next week.
