### ISSUE TITLE
Feature: Relay command implementation

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/BB84.Notifications#55]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Having an out of the box `ICommand` implementation  to separate the semantics and the object that invokes a command from the logic that executes the command just seems reasonable.

**Describe alternatives you've considered**
Different additional packages ..

**Comment by BoBoBaSs84** [comment]
From the perspective to have everything in one place it seems as a good idea.
